<?php

namespace Database\Seeders;

use App\Models\Job;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'System Admin',
            'email' => 'admin@jobboard.com',
            'password' => 'password123',
            'role' => 'admin',
        ]);

        User::create([
            'name' => 'Ahmed Hassan',
            'email' => 'ahmed@example.com',
            'password' => 'password123',
            'role' => 'candidate',
            'age' => 26,
            'job_title' => 'Laravel Developer',
            'phone' => '01001234567',
            'skills' => 'PHP, Laravel, MySQL, HTML, CSS, JavaScript, Git',
            'description' => 'Backend developer with 3 years of experience building web applications with Laravel.',
        ]);

        $jobs = [
            [
                'title' => 'Senior Laravel Developer',
                'description' => "We are looking for an experienced Laravel developer to join our growing team. You will build and maintain high-quality web applications, work with a modern stack, and collaborate with a talented engineering team.\n\nResponsibilities:\n- Develop new features with Laravel and PHP\n- Write clean, maintainable and tested code\n- Work closely with front-end developers and designers\n- Optimize application performance\n\nRequirements:\n- 3+ years of experience with Laravel\n- Strong knowledge of MySQL and relational databases\n- Experience with REST APIs and Git",
                'required_skills' => 'PHP, Laravel, MySQL, Git, REST API, JavaScript',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'hybrid',
                'salary' => 60000,
                'deadline' => now()->addDays(30),
            ],
            [
                'title' => 'Frontend Developer (React)',
                'description' => "Join our product team as a Frontend Developer. You will build responsive, accessible user interfaces with React and modern tooling.\n\nResponsibilities:\n- Build reusable React components\n- Implement pixel-perfect UIs from designs\n- Collaborate with backend developers\n\nRequirements:\n- 2+ years with React\n- Solid HTML, CSS and JavaScript skills\n- Experience with state management (Redux or Zustand)",
                'required_skills' => 'React, HTML, CSS, JavaScript, Redux, Tailwind',
                'category' => 'IT',
                'location' => 'Alexandria',
                'work_type' => 'remote',
                'salary' => 45000,
                'deadline' => now()->addDays(21),
            ],
            [
                'title' => 'Data Analyst',
                'description' => "We need a data analyst to turn raw data into actionable insights. You will work with SQL, spreadsheets and BI tools.\n\nResponsibilities:\n- Analyze business data and prepare reports\n- Build dashboards\n- Support decision-making with data\n\nRequirements:\n- Experience with SQL and Excel\n- Knowledge of Python is a plus\n- Strong analytical thinking",
                'required_skills' => 'SQL, Excel, Python, Power BI, Statistics',
                'category' => 'Data Science',
                'location' => 'Giza',
                'work_type' => 'on-site',
                'salary' => 35000,
                'deadline' => now()->addDays(15),
            ],
            [
                'title' => 'UI/UX Designer',
                'description' => "We are looking for a creative UI/UX designer to design intuitive interfaces for web and mobile products.\n\nResponsibilities:\n- Create wireframes, prototypes and mockups\n- Conduct user research\n- Collaborate with developers on implementation\n\nRequirements:\n- Portfolio of design work\n- Proficiency in Figma\n- Understanding of design systems and usability",
                'required_skills' => 'Figma, Adobe XD, Wireframing, Prototyping, UX Research',
                'category' => 'Design',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 40000,
                'deadline' => now()->addDays(45),
            ],
            [
                'title' => 'Marketing Specialist',
                'description' => "Help us grow our brand. You will plan and execute marketing campaigns across digital channels.\n\nResponsibilities:\n- Manage social media accounts\n- Create marketing content\n- Run and analyze ad campaigns\n\nRequirements:\n- Experience with digital marketing\n- Excellent writing skills\n- Knowledge of SEO and Google Analytics",
                'required_skills' => 'SEO, Google Analytics, Social Media, Content Writing, Email Marketing',
                'category' => 'Marketing',
                'location' => 'Cairo',
                'work_type' => 'hybrid',
                'salary' => 28000,
                'deadline' => now()->addDays(60),
            ],
            [
                'title' => 'DevOps Engineer',
                'description' => "We are looking for a DevOps engineer to build and maintain our cloud infrastructure and CI/CD pipelines.\n\nResponsibilities:\n- Manage cloud infrastructure (AWS)\n- Build CI/CD pipelines\n- Monitor system health and performance\n\nRequirements:\n- Experience with AWS or Azure\n- Knowledge of Docker and Kubernetes\n- Scripting with Bash or Python",
                'required_skills' => 'AWS, Docker, Kubernetes, Linux, CI/CD, Bash, Python',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 75000,
                'deadline' => now()->addDays(10),
            ],
            [
                'title' => 'Flutter Mobile Developer',
                'description' => "Build beautiful cross-platform mobile apps with Flutter.\n\nResponsibilities:\n- Develop mobile applications with Flutter\n- Integrate REST APIs\n- Publish apps to the app stores\n\nRequirements:\n- Experience with Dart and Flutter\n- Understanding of mobile UI patterns\n- Experience with REST APIs",
                'required_skills' => 'Dart, Flutter, REST API, Firebase, Mobile Development',
                'category' => 'IT',
                'location' => 'Mansoura',
                'work_type' => 'hybrid',
                'salary' => 42000,
                'deadline' => now()->addDays(25),
            ],
            [
                'title' => 'HR Coordinator',
                'description' => "Support our HR team with recruitment, onboarding and employee engagement.\n\nResponsibilities:\n- Coordinate recruitment processes\n- Handle onboarding of new employees\n- Maintain HR records\n\nRequirements:\n- Excellent communication skills\n- Organizational skills\n- Experience in HR is a plus",
                'required_skills' => 'Communication, Recruitment, Microsoft Office, HR Management',
                'category' => 'HR',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 22000,
                'deadline' => now()->addDays(50),
            ],
            [
                'title' => 'Accountant',
                'description' => "Manage financial records, prepare reports and ensure compliance.\n\nResponsibilities:\n- Handle accounts payable and receivable\n- Prepare financial statements\n- Support tax filings\n\nRequirements:\n- Accounting degree\n- Knowledge of accounting software\n- Attention to detail",
                'required_skills' => 'Accounting, Excel, ERP, Financial Reporting, QuickBooks',
                'category' => 'Finance',
                'location' => 'Alexandria',
                'work_type' => 'on-site',
                'salary' => 30000,
                'deadline' => now()->addDays(35),
            ],
            [
                'title' => 'Cybersecurity Analyst',
                'description' => "Protect our systems and data from security threats. You will monitor, analyze and respond to security incidents.\n\nResponsibilities:\n- Monitor systems for security threats\n- Perform vulnerability assessments\n- Implement security policies\n\nRequirements:\n- Experience with security tools and best practices\n- Knowledge of network protocols\n- Familiarity with penetration testing",
                'required_skills' => 'Cybersecurity, Networking, Penetration Testing, Linux, SIEM',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'remote',
                'salary' => 70000,
                'deadline' => now()->addDays(40),
            ],
            [
                'title' => 'Backend Developer (Node.js)',
                'description' => "Build scalable backend services with Node.js and modern JavaScript tooling.\n\nResponsibilities:\n- Develop RESTful APIs with Node.js\n- Design database schemas\n- Optimize server performance\n\nRequirements:\n- 2+ years with Node.js and Express\n- Experience with MongoDB or PostgreSQL\n- Knowledge of TypeScript is a plus",
                'required_skills' => 'Node.js, Express, TypeScript, MongoDB, PostgreSQL, REST API',
                'category' => 'IT',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 55000,
                'deadline' => now()->addDays(28),
            ],
            [
                'title' => 'Machine Learning Engineer',
                'description' => "Design and deploy machine learning models that power our products.\n\nResponsibilities:\n- Build and train ML models\n- Deploy models to production\n- Collaborate with data scientists\n\nRequirements:\n- Strong Python skills\n- Experience with TensorFlow or PyTorch\n- Understanding of ML algorithms",
                'required_skills' => 'Python, TensorFlow, PyTorch, Machine Learning, SQL',
                'category' => 'Data Science',
                'location' => 'Giza',
                'work_type' => 'hybrid',
                'salary' => 80000,
                'deadline' => now()->addDays(55),
            ],
            [
                'title' => 'Product Manager',
                'description' => "Own the product roadmap and deliver features that users love.\n\nResponsibilities:\n- Define product vision and roadmap\n- Gather and prioritize requirements\n- Coordinate with engineering and design\n\nRequirements:\n- Experience in product management\n- Strong communication skills\n- Data-driven decision making",
                'required_skills' => 'Product Management, Agile, Scrum, Roadmapping, Analytics',
                'category' => 'Management',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 65000,
                'deadline' => now()->addDays(48),
            ],
            [
                'title' => 'Content Writer',
                'description' => "Create engaging content for our blog, website and marketing campaigns.\n\nResponsibilities:\n- Write blog posts and articles\n- Create social media content\n- Optimize content for SEO\n\nRequirements:\n- Excellent writing skills in English\n- Knowledge of SEO best practices\n- Ability to research topics",
                'required_skills' => 'Content Writing, SEO, Research, Blogging, Copywriting',
                'category' => 'Marketing',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 20000,
                'deadline' => now()->addDays(32),
            ],
            [
                'title' => 'Graphic Designer',
                'description' => "Design visual content for branding, marketing and digital products.\n\nResponsibilities:\n- Create brand assets and layouts\n- Design marketing materials\n- Collaborate with the marketing team\n\nRequirements:\n- Proficiency in Photoshop and Illustrator\n- Strong design portfolio\n- Understanding of color and typography",
                'required_skills' => 'Photoshop, Illustrator, Branding, Typography, Figma',
                'category' => 'Design',
                'location' => 'Alexandria',
                'work_type' => 'hybrid',
                'salary' => 26000,
                'deadline' => now()->addDays(37),
            ],
            [
                'title' => 'Customer Support Specialist',
                'description' => "Help customers with questions and issues while ensuring a great experience.\n\nResponsibilities:\n- Respond to customer inquiries\n- Troubleshoot basic issues\n- Document feedback\n\nRequirements:\n- Excellent communication skills\n- Patience and empathy\n- Basic computer skills",
                'required_skills' => 'Communication, Customer Service, Problem Solving, Zendesk',
                'category' => 'Support',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 18000,
                'deadline' => now()->addDays(18),
            ],
            [
                'title' => 'QA Engineer',
                'description' => "Ensure software quality through manual and automated testing.\n\nResponsibilities:\n- Write and execute test cases\n- Build automated test suites\n- Report and track bugs\n\nRequirements:\n- Experience with testing tools\n- Knowledge of SQL\n- Attention to detail",
                'required_skills' => 'QA Testing, Selenium, Automated Testing, SQL, Bug Tracking',
                'category' => 'IT',
                'location' => 'Mansoura',
                'work_type' => 'hybrid',
                'salary' => 33000,
                'deadline' => now()->addDays(24),
            ],
            [
                'title' => 'Database Administrator',
                'description' => "Manage and optimize our database systems for performance and reliability.\n\nResponsibilities:\n- Install and configure databases\n- Monitor performance and optimize queries\n- Manage backups and recovery\n\nRequirements:\n- Experience with MySQL or PostgreSQL\n- Knowledge of database tuning\n- Familiarity with cloud databases",
                'required_skills' => 'MySQL, PostgreSQL, Database Tuning, Backup & Recovery, Linux',
                'category' => 'IT',
                'location' => 'Giza',
                'work_type' => 'on-site',
                'salary' => 48000,
                'deadline' => now()->addDays(42),
            ],
            [
                'title' => 'Cloud Architect',
                'description' => "Design scalable and secure cloud architectures that power our products.\n\nResponsibilities:\n- Design cloud infrastructure on AWS or Azure\n- Define security and cost policies\n- Lead migration of legacy systems\n\nRequirements:\n- 5+ years in cloud engineering\n- Strong AWS or Azure certification\n- Experience with microservices and containerization",
                'required_skills' => 'AWS, Azure, Docker, Kubernetes, Microservices, Cloud Security',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 95000,
                'deadline' => now()->addDays(45),
            ],
            [
                'title' => 'Data Engineer',
                'description' => "Build robust data pipelines that turn raw data into reliable, queryable datasets.\n\nResponsibilities:\n- Design and maintain ETL pipelines\n- Optimize data storage and processing\n- Ensure data quality and governance\n\nRequirements:\n- Experience with Python and SQL\n- Knowledge of Airflow or Spark\n- Familiarity with cloud data warehouses",
                'required_skills' => 'Python, SQL, Airflow, Spark, AWS, Data Pipelines',
                'category' => 'Data Science',
                'location' => 'Giza',
                'work_type' => 'hybrid',
                'salary' => 72000,
                'deadline' => now()->addDays(38),
            ],
            [
                'title' => 'Motion Graphics Designer',
                'description' => "Create eye-catching motion graphics and animations for our digital campaigns.\n\nResponsibilities:\n- Produce animated assets for web and social media\n- Create video intros and product demos\n- Collaborate with the design team\n\nRequirements:\n- Proficiency in After Effects and Premiere\n- Strong portfolio of motion work\n- Understanding of timing and storytelling",
                'required_skills' => 'After Effects, Premiere, Animation, Video Editing, Cinema 4D',
                'category' => 'Design',
                'location' => 'Alexandria',
                'work_type' => 'remote',
                'salary' => 38000,
                'deadline' => now()->addDays(29),
            ],
            [
                'title' => 'SEO Specialist',
                'description' => "Improve our organic visibility and drive qualified traffic through technical and content SEO.\n\nResponsibilities:\n- Audit and optimize on-page SEO\n- Build link acquisition strategies\n- Track rankings and keyword performance\n\nRequirements:\n- 2+ years in SEO\n- Experience with Google Analytics and Search Console\n- Strong analytical skills",
                'required_skills' => 'SEO, Google Analytics, Ahrefs, Content Strategy, Keyword Research',
                'category' => 'Marketing',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 24000,
                'deadline' => now()->addDays(26),
            ],
            [
                'title' => 'Financial Analyst',
                'description' => "Provide financial insights and forecasts to support strategic business decisions.\n\nResponsibilities:\n- Build financial models and forecasts\n- Analyze revenue and cost drivers\n- Prepare monthly management reports\n\nRequirements:\n- Degree in Finance or Accounting\n- Advanced Excel skills\n- Experience with financial modeling",
                'required_skills' => 'Excel, Financial Modeling, Forecasting, Power BI, SQL',
                'category' => 'Finance',
                'location' => 'Cairo',
                'work_type' => 'hybrid',
                'salary' => 41000,
                'deadline' => now()->addDays(40),
            ],
            [
                'title' => 'Sales Account Manager',
                'description' => "Own key client relationships and grow revenue through consultative selling.\n\nResponsibilities:\n- Manage a portfolio of client accounts\n- Identify upsell and cross-sell opportunities\n- Prepare proposals and negotiate contracts\n\nRequirements:\n- Proven B2B sales experience\n- Excellent communication skills\n- CRM experience (Salesforce or HubSpot)",
                'required_skills' => 'B2B Sales, CRM, Negotiation, Communication, HubSpot',
                'category' => 'Sales',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 32000,
                'deadline' => now()->addDays(33),
            ],
            [
                'title' => 'E-commerce Manager',
                'description' => "Drive our online store growth across platforms and marketplaces.\n\nResponsibilities:\n- Manage the online storefront and listings\n- Plan promotions and product launches\n- Analyze sales and conversion data\n\nRequirements:\n- Experience with e-commerce platforms\n- Digital marketing knowledge\n- Data-driven mindset",
                'required_skills' => 'E-commerce, Shopify, Digital Marketing, Google Analytics, Marketplace',
                'category' => 'Marketing',
                'location' => 'Alexandria',
                'work_type' => 'hybrid',
                'salary' => 36000,
                'deadline' => now()->addDays(31),
            ],
            [
                'title' => 'IT Support Engineer',
                'description' => "Keep our internal systems running smoothly and support our employees.\n\nResponsibilities:\n- Troubleshoot hardware and software issues\n- Manage user accounts and access\n- Maintain network and systems health\n\nRequirements:\n- Experience with Windows and Linux\n- Networking fundamentals\n- Great customer service skills",
                'required_skills' => 'Windows, Linux, Networking, Active Directory, Troubleshooting',
                'category' => 'IT',
                'location' => 'Mansoura',
                'work_type' => 'on-site',
                'salary' => 27000,
                'deadline' => now()->addDays(22),
            ],
            [
                'title' => 'Business Intelligence Developer',
                'description' => "Transform data into dashboards and reports that guide business decisions.\n\nResponsibilities:\n- Build BI dashboards and reports\n- Design data models\n- Partner with business teams on analytics\n\nRequirements:\n- Experience with Power BI or Tableau\n- Strong SQL skills\n- Understanding of data modeling",
                'required_skills' => 'Power BI, Tableau, SQL, Data Modeling, DAX, Dashboards',
                'category' => 'Data Science',
                'location' => 'Giza',
                'work_type' => 'remote',
                'salary' => 52000,
                'deadline' => now()->addDays(47),
            ],
            [
                'title' => 'Mobile App Tester',
                'description' => "Ensure our mobile applications are reliable and bug-free before release.\n\nResponsibilities:\n- Write and execute test cases for mobile apps\n- Report bugs and track fixes\n- Perform regression testing\n\nRequirements:\n- Experience with iOS and Android testing\n- Attention to detail\n- Familiarity with test management tools",
                'required_skills' => 'Mobile Testing, iOS, Android, Test Case Design, JIRA',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'hybrid',
                'salary' => 25000,
                'deadline' => now()->addDays(24),
            ],
            [
                'title' => 'Technical Recruiter',
                'description' => "Attract and hire top technical talent across our engineering teams.\n\nResponsibilities:\n- Source and screen candidates\n- Coordinate interviews and offers\n- Build a strong talent pipeline\n\nRequirements:\n- Experience in technical recruiting\n- Familiarity with software roles\n- Strong communication skills",
                'required_skills' => 'Recruiting, Sourcing, Interviewing, ATS, Communication',
                'category' => 'HR',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 26000,
                'deadline' => now()->addDays(28),
            ],
            [
                'title' => 'Supply Chain Coordinator',
                'description' => "Coordinate the flow of goods from suppliers to customers with minimal disruption.\n\nResponsibilities:\n- Manage purchase orders and deliveries\n- Track inventory levels\n- Liaise with suppliers and logistics partners\n\nRequirements:\n- Experience in supply chain or logistics\n- Strong organizational skills\n- Proficiency in Excel",
                'required_skills' => 'Logistics, Inventory Management, Procurement, Excel, ERP',
                'category' => 'Logistics',
                'location' => 'Alexandria',
                'work_type' => 'on-site',
                'salary' => 29000,
                'deadline' => now()->addDays(35),
            ],
            [
                'title' => 'Legal Assistant',
                'description' => "Support our legal team with contracts, compliance and documentation.\n\nResponsibilities:\n- Draft and review contracts\n- Maintain legal records\n- Assist with compliance matters\n\nRequirements:\n- Law degree or legal studies background\n- Strong written communication\n- Attention to detail",
                'required_skills' => 'Contracts, Legal Research, Documentation, Compliance, Communication',
                'category' => 'Legal',
                'location' => 'Cairo',
                'work_type' => 'on-site',
                'salary' => 30000,
                'deadline' => now()->addDays(44),
            ],
            [
                'title' => 'Online Instructor',
                'description' => "Create and deliver engaging online courses for our e-learning platform.\n\nResponsibilities:\n- Develop course materials and lessons\n- Deliver live and recorded sessions\n- Support student questions and progress\n\nRequirements:\n- Strong subject expertise\n- Experience teaching or training\n- Comfort with online tools",
                'required_skills' => 'Teaching, Course Design, Communication, E-learning, Curriculum',
                'category' => 'Education',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 21000,
                'deadline' => now()->addDays(36),
            ],
            [
                'title' => 'Database Developer',
                'description' => "Develop and optimize database-driven applications and stored procedures.\n\nResponsibilities:\n- Write complex SQL queries and procedures\n- Design database schemas\n- Improve query performance\n\nRequirements:\n- Strong SQL and database skills\n- Experience with MySQL or SQL Server\n- Familiarity with ORMs",
                'required_skills' => 'SQL, MySQL, SQL Server, Stored Procedures, Query Tuning',
                'category' => 'IT',
                'location' => 'Giza',
                'work_type' => 'hybrid',
                'salary' => 44000,
                'deadline' => now()->addDays(39),
            ],
            [
                'title' => 'Product Designer',
                'description' => "Design intuitive, beautiful product experiences from concept to launch.\n\nResponsibilities:\n- Own the end-to-end product design process\n- Create wireframes, prototypes and design systems\n- Run usability testing\n\nRequirements:\n- Strong product design portfolio\n- Proficiency in Figma\n- Experience with design systems",
                'required_skills' => 'Figma, UX, UI Design, Prototyping, Design Systems, Usability',
                'category' => 'Design',
                'location' => 'Remote',
                'work_type' => 'remote',
                'salary' => 43000,
                'deadline' => now()->addDays(34),
            ],
            [
                'title' => 'Kubernetes DevOps Engineer',
                'description' => "Operate and scale our Kubernetes clusters and cloud infrastructure.\n\nResponsibilities:\n- Manage Kubernetes clusters and workloads\n- Build CI/CD pipelines\n- Automate infrastructure with IaC\n\nRequirements:\n- Hands-on Kubernetes experience\n- Strong Linux and scripting skills\n- Familiarity with Terraform",
                'required_skills' => 'Kubernetes, Docker, Terraform, CI/CD, AWS, Linux',
                'category' => 'IT',
                'location' => 'Cairo',
                'work_type' => 'hybrid',
                'salary' => 78000,
                'deadline' => now()->addDays(50),
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}
